services:
    database:
     container_name: clients_database
     image: mariadb:10.5.8
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: clients
       MYSQL_USER: root
       MYSQL_PASSWORD: root
     volumes:
       - ./var/dbdata:/var/lib/mysql
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - "8082:80"
      environment:
        PMA_HOST: clients_database
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
        UPLOAD_LIMIT: 1G
        MEMORY_LIMIT: 512M
        MAX_EXECUTION_TIME: 0
      restart: always
      links:
        - database
